# Set the token in Travis environment settings instead defining here.
env:
  global:
    - CODECOV_TOKEN="2628ff15-ee87-46b4-9b58-de26194b6377"
    - CC_TEST_REPORTER_ID="8cdc2586c2a4650d0ee59c36c6f36b94a116fb3ca44f41aa177a1678bc651671"
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
install: true

#For Code Climate Test Coverage
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mvn clean install  
after_success:
#For Code Climate Test Coverage
  #Solution from https://github.com/codeclimate/test-reporter/issues/259#issuecomment-374280649
  # Format jacoco coverage result
  - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage --input-type jacoco -o coverage/codeclimate.jacoco.json target/site/jacoco/jacoco.xml
  # Format cobertura coverage result
  - ./cc-test-reporter format-coverage --input-type cobertura -o coverage/codeclimate.cobertura.json target/site/cobertura/coverage.xml
  # Sum both coverage parts into coverage/codeclimate.json
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
  # Upload coverage/codeclimate.json
  - ./cc-test-reporter upload-coverage

#For Codecov Test Coverage
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
